// Run this whenever you add new files to assets/other/:
//   node scripts/gen-gallery.js
//
// It scans assets/other/ and writes js/gallery-assets.js,
// which gallery.html uses to render the grid automatically.

const fs   = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '..', 'assets', 'other');
const OUT_FILE   = path.join(__dirname, '..', 'js', 'gallery-assets.js');

const IMG_EXTS = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp']);
const VID_EXTS = new Set(['.mp4', '.mov', '.webm', '.m4v']);

// Files to exclude from the gallery (used elsewhere on the site)
const SKIP = new Set(['towerCraneBanner.jpg']);

const files = fs.readdirSync(ASSETS_DIR)
  .filter(f => {
    if (SKIP.has(f)) return false;
    const ext = path.extname(f).toLowerCase();
    return IMG_EXTS.has(ext) || VID_EXTS.has(ext);
  })
  .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));

const content =
  `// Auto-generated by scripts/gen-gallery.js — do not edit manually.\n` +
  `// Run: node scripts/gen-gallery.js\n` +
  `const GALLERY_ASSETS = ${JSON.stringify(files, null, 2)};\n`;

fs.writeFileSync(OUT_FILE, content, 'utf8');
console.log(`✓ ${files.length} assets written to js/gallery-assets.js`);
